// Copyright (c) 2022 Jonathan Lang

//---------- ----------------------------- ----------
//---------- !!! AUTOGENERATED CONTENT !!! ----------
//---------- ----------------------------- ----------

//Runtime Monitoring
//File generated: 2022-09-06 23:50:44Z
//Please dont change the contents of this file. Otherwise IL2CPP runtime may not work with runtime monitoring!
//Ensure that this file is located in Assembly-CSharp. Otherwise this file may not compile.
//If this file contains any errors please contact me and/or create an issue in the linked repository.
//https://github.com/JohnBaracuda/Runtime-Monitoring

#if ENABLE_IL2CPP && !DISABLE_MONITORING

internal class IL2CPP_AOT
{
    //Field Profiles
    
    //FieldProfile<Player, Vector3>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.FieldProfile<Player, UnityEngine.Vector3> AOT_GENERATED_TYPE_0;
    
    //FieldProfile<Player, Enum32>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.FieldProfile<Player, Baracuda.Monitoring.IL2CPP.Enum32> AOT_GENERATED_TYPE_1;
    
    //FieldProfile<FPSMonitor, float>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.FieldProfile<Baracuda.Monitoring.Modules.FPSMonitor, System.Single> AOT_GENERATED_TYPE_6;
    
    //FieldProfile<SystemMonitor, string>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.FieldProfile<Baracuda.Monitoring.Modules.SystemMonitor, System.String> AOT_GENERATED_TYPE_8;
    
    //FieldProfile<GameManager, int>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.FieldProfile<Baracuda.Monitoring.Example.Scripts.GameManager, System.Int32> AOT_GENERATED_TYPE_9;
    
    //FieldProfile<PlayerMovement, bool>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.FieldProfile<Baracuda.Monitoring.Example.Scripts.PlayerMovement, System.Boolean> AOT_GENERATED_TYPE_12;
    
    //FieldProfile<PlayerMovement, int>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.FieldProfile<Baracuda.Monitoring.Example.Scripts.PlayerMovement, System.Int32> AOT_GENERATED_TYPE_13;
    
    //FieldProfile<PlayerMovement, float>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.FieldProfile<Baracuda.Monitoring.Example.Scripts.PlayerMovement, System.Single> AOT_GENERATED_TYPE_14;
    
    //FieldProfile<PlayerWeapon, int>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.FieldProfile<Baracuda.Monitoring.Example.Scripts.PlayerWeapon, System.Int32> AOT_GENERATED_TYPE_16;
    
    //FieldProfile<ShootingTarget, float>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.FieldProfile<Baracuda.Monitoring.Example.Scripts.ShootingTarget, System.Single> AOT_GENERATED_TYPE_17;

    //------------------------------------------------------------------------------------------------------------------

    //Property Profiles
    
    //PropertyProfile<Player, Vector3>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.PropertyProfile<Player, UnityEngine.Vector3> AOT_GENERATED_TYPE_2;
    
    //PropertyProfile<ConsoleMonitor, Queue<string>>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.PropertyProfile<Baracuda.Monitoring.Modules.ConsoleMonitor, System.Collections.Generic.Queue<System.String>> AOT_GENERATED_TYPE_4;
    
    //PropertyProfile<ConsoleMonitor, string>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.PropertyProfile<Baracuda.Monitoring.Modules.ConsoleMonitor, System.String> AOT_GENERATED_TYPE_5;
    
    //PropertyProfile<FPSMonitor, int>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.PropertyProfile<Baracuda.Monitoring.Modules.FPSMonitor, System.Int32> AOT_GENERATED_TYPE_7;
    
    //PropertyProfile<GameManager, GameState>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.PropertyProfile<Baracuda.Monitoring.Example.Scripts.GameManager, Baracuda.Monitoring.Example.Scripts.GameState> AOT_GENERATED_TYPE_10;
    
    //PropertyProfile<PlayerMovement, Vector3>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.PropertyProfile<Baracuda.Monitoring.Example.Scripts.PlayerMovement, UnityEngine.Vector3> AOT_GENERATED_TYPE_15;

    //------------------------------------------------------------------------------------------------------------------

    //Event Profiles
    
    //EventProfile<Player, Action>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.EventProfile<Player, System.Action> AOT_GENERATED_TYPE_3;
    
    //EventProfile<GameManager, Action<GameState>>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Source.Profiles.EventProfile<Baracuda.Monitoring.Example.Scripts.GameManager, System.Action<Baracuda.Monitoring.Example.Scripts.GameState>> AOT_GENERATED_TYPE_11;

    //------------------------------------------------------------------------------------------------------------------

    //Method Profiles

    //------------------------------------------------------------------------------------------------------------------

    //Value Processor Method Definitions

    [UnityEngine.Scripting.PreserveAttribute]
    [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.NoOptimization)]
    private static void AOT()
    {
        Baracuda.Monitoring.IL2CPP.AOTBridge.AOTEnumerable<System.String>();
    }
}

#endif //ENABLE_IL2CPP && !DISABLE_MONITORING

//----------------------------------------------------------------------------------------------------------------------

//--- Stats ---

//General

//Monitored Member:               42
//Monitored Member Instance:      42

//MemberInfo

//Monitored Events:                2
//Monitored Events Instance:       2
//Monitored Fields:               32
//Monitored Fields Instance:      32
//Monitored Properties:            8
//Monitored Properties Instance:   8

//Monitored Types

//Monitored Action:                1
//Monitored Action<GameState>:     1
//Monitored bool:                  3
//Monitored Enum32:                1
//Monitored float:                 4
//Monitored GameState:             1
//Monitored int:                   5
//Monitored Queue<string>:         1
//Monitored string:               21
//Monitored Vector3:               3

//----------------------------------------------------------------------------------------------------------------------

//If this file contains any errors please contact me and/or create an issue in the linked repository.
//https://github.com/JohnBaracuda/Runtime-Monitoring